### ISSUE TITLE
Migrate plugin under tox-dev

### ISSUE THREAD

**Issue by ssbarnea** [ymyzk/tox-gh-actions#79]
I am a (tox/pytest/sphinx) plugin author myself and I am worried about plugins relying on a single person. Too often I was hit by either abandonware or other problems related to the fact that the project relied on a single person, which lost interest, or become permanently unavailable (yep, we all have an unknown expiration date).

Few years ago I started moving my projects to github orgs aimed at maintaining plugins long term, such as @tox-dev @pytest-dev @sphinx-contrib @jazzband  or @pycqa. I made a personal rule: avoid starting to use any plugin that is not already doing that (to some extent I do the same with python libraries in general).

Please really consider doing that move, you will keep your full owner control over the repository and I really doubt anyone else would step-in to make changes unless you become unavailable.

Shortly, future proof your kid project ;)

**Comment by ssbarnea** [comment]
Oops, I missed that I asked that already on https://github.com/ymyzk/tox-gh-actions/issues/57

**Comment by ymyzk** [comment]
Thanks for filing a ticket. I understand your concern.

As you noticed in #57, I feel it's a bit difficult to work with one of @tox-dev members at this point for various reasons.

If problems are resolved in the future, I'm happy to think about migration to an organization again.

In the worst case scenario, someone can make a folk as this is an OSS 🙂 but I'd like to avoid this worst case scenario as much as possible.

**Comment by ymyzk** [comment]
Thank you very much for the nice advice! I'll keep this in my mind and would like to try when I have a chance in the future. Timezone difference can make it difficult to communicate synchronously though 🙂 

For this specific topic on migrating to tox-dev, I would not want to spend extra effort considering discussions so far. (JFYI, there's another discussion in tox-dev/tox as well.) It has been non-constructive and I would like to focus on helping users of this plugin rather than spending efforts on communicating with tox-dev.
